### ISSUE TITLE
Record of guessed words

### ISSUE THREAD

**Issue by davidthehat** [davidthehat/DiscordWordleBot#2]
Bot should, upon request, report the words it guessed in a particular attempt.

Example implementation:

INPUT
/guesses word:polka

OUTPUT
aeros
clint
dumpy
acker
polka

**Comment by Tyler-Seliber** [comment]
This site shows how you can change text color on Discord using markdown, it would be neat if you could implement this as well to show which letters were correct. [https://rebane2001.com/discord-colored-text-generator/](https://rebane2001.com/discord-colored-text-generator/)

Example (it can also be specified as a spoiler for discord):
![Screenshot 2023-02-28 at 11 19 16 AM](https://user-images.githubusercontent.com/42685071/221913487-7083e756-1c2a-4013-9ca6-e811338422b1.png)

**Comment by davidthehat** [comment]
An interesting approach. Will consider.
