### ISSUE TITLE
Updates to Custom Starting Word

### ISSUE THREAD

**Issue by Tyler-Seliber** [davidthehat/DiscordWordleBot#4]
When using /playwordle with a custom starting word, it would be nice for the output to reflect that a different starting word has been selected. This makes it more clear that the bot isn't choosing it's own word without the user needing to hover over the original command to see the word. It also can clarify that the bot didn't choose its own word without other users receiving a spoiler for the starting word.

For example:

`/playwordle word:chair` can output:
```
Wordle 620 5/6 :robot:
Starting word: ||CHAIR||
🟨⬛🟨⬛⬛
⬛⬛⬛🟩⬛
⬛⬛🟨🟨⬛
⬛🟨⬛🟨⬛
🟩🟩🟩🟩🟩
```
The starting word will be put behind a spoiler flag so other users who haven't played the Wordle yet won't see any potential clues for the game. 

Also, the description for the command could be updated to clarify that this is the starting word to be played with. An example could be: "The starting word to play the wordle with (overrides date options)"

**Comment by davidthehat** [comment]
To clarify, the word parameter in /playwordle changes the TARGET word, not the starting word. This suggestion has essentially been added with this commit https://github.com/davidthehat/DiscordWordleBot/commit/8fa0e28b247e72d5e8ab419f873b186f9eb62171.
